package dialogos;
import logica.Cliente;

/**
 * FECHA ==> 2019-05-26.
 * Ventana para agregar los datos de un cliente a una venta.
 * @author Luis Alejandro Gómez C.
 * @version 1.0.0
 */
public class IngresarCliente extends javax.swing.JDialog 
{
    /**
     * Cliente que se registra en esta ventana.
     */
    private Cliente cliente;
    
    /**
     * Creates new form IngresarCliente
     */
    public IngresarCliente(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.cliente = new Cliente("","","");
    }

    /**
     * Obtiene el cliente ingresado en esta ventana.
     * @return Cliente registrado en la ventana.
     */
    public Cliente getCliente() 
    {
        return cliente;
    }

    /**
     * Modifica el cliente de la ventana.
     * @param cliente Cliente de reemplazo.
     */
    public void setCliente(Cliente cliente) 
    {
        this.cliente = cliente;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        txtEncabezado = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        nit = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEncabezado.setBackground(new java.awt.Color(36, 52, 81));

        txtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
        });

        txtEncabezado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccion.png"))); // NOI18N
        txtEncabezado.setText("      Agregar Cliente");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalir)
                .addContainerGap())
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalir)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(txtEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        nombre.setText("Nombre:");

        campoNombre.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        nit.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        nit.setText("Cedúla:");

        campoCedula.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        telefono.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        telefono.setText("Teléfono:");

        campoTelefono.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(20, 60, 108));
        btnAceptar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(176, 95, 95));
        btnCancelar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nit)
                                        .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telefono)
                                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnCancelar)
                        .addGap(73, 73, 73)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTelefono))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(nit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked

    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.cliente = new Cliente("","","");
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombreC = this.campoNombre.getText() + "";
        String cedulaC = this.campoCedula.getText() + "";
        String telefonoC = this.campoTelefono.getText() + "";
        this.cliente = new Cliente(nombreC, cedulaC, telefonoC);

        this.campoNombre.setText("");
        this.campoCedula.setText("");
        this.campoTelefono.setText("");        
        this.dispose();
//        try
//        {
//            String nombre = this.campoNombre.getText();
//            String cedula = this.campoCedula.getText();
//            String telefono = this.campoTelefono.getText();
//            if(!nombre.equals("")&&!cedula.equals(""))
//            {                
//                this.cliente=new Cliente(nombre, cedula);
//                if(telefono!=null)
//                {
//                    cliente.setTelefono(telefono);
//                }
//                JOptionPane.showMessageDialog(null,"Cliente "+cliente.getNombre()+" Agregado a la Venta");
//                campoNombre.setText("");
//                campoCedula.setText("");
//                campoTelefono.setText("");
//                this.dispose();
//            }     
//            else{
//                JOptionPane.showMessageDialog(null,"Por Favor Escriba El Nombre y Cedula del Cliente");
//            }
//        }
//        catch(Exception e) 
//        {
//            JOptionPane.showMessageDialog(null,"No se pudó Agregar Client \n Datos Invalidos O espacios en Blanco");
//        }       
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel nit;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel txtEncabezado;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
